version: "3.9"
services:
  inpigritas-node-1:
    container_name: inpigiritas-node-1
    image: inpigritas:latest
    restart: always
    user: "1000:1000"
    environment:
      - INPIG_PORT=8080
      - INPIG_PEER_PORT=8081
    networks:
      - local
    ports:
      - "8080:8080"

  inpigritas-node-2:
    container_name: inpigiritas-node-2
    image: inpigritas:latest
    restart: always
    user: "1000:1000"
    environment:
      - INPIG_PORT=8081
      - INPIG_PEER_PORT=8080
    networks:
      - local
    ports:
      - "8081:8081"

networks:
  local:
    name: local
    driver: bridge
