version: "3.9"
services:
  inpigritas-node-1:
    container_name: inpigiritas-node-1
    image: inpigritas:latest
    restart: always
    user: "1000:1000"
    environment:
      - INPIG_PEER_HOST=inpigritas-node-2
    networks:
      - local
    ports:
      - "8080:8080"

  inpigritas-node-2:
    container_name: inpigiritas-node-2
    image: inpigritas:latest
    restart: always
    user: "1000:1000"
    environment:
      - INPIG_PEER_HOST=inpigritas-node-1
    networks:
      - local

networks:
  local:
    name: local
    driver: bridge
